<?php

use Drupal\file\Entity\File;
use Drupal\ai\OperationType\GenericType\ImageFile;
use Drupal\ai_provider_yolov8\OperationType\ImageObjectDetection\ImageObjectDetectionInput;

/**
 * @file
 * Primary module hooks for AI Focal Point module.
 */

 
function ai_focal_point_page_top(array &$page_top) : void {
  $file = File::load(1);
  
  $input = new ImageObjectDetectionInput($file);

  $objects_detected =  \Drupal::service('ai.provider')
  ->createInstance('ai_yolov8', [])
  ->imageObjectDetection($input, 'yolov8')
  ->getNormalized();
  
  $objects = [];
  foreach ($objects_detected as $item) {
    $objects[] = $item->getDetection();
  }
  
  $file_path = \Drupal::service('file_system')->realpath($file->getFileUri());
  [$width, $height] = getimagesize($file_path);

  $calculation =  \Drupal::service('ai_focal_point.calculator')
  ->computeFocalPoint($objects, $width, $height);

  print_r([$calculation['x'], $calculation['y']]);
}
